<a href="https://colab.research.google.com/github/ahtisham-maliik/ML-Exercise/blob/main/ML%20Logistic%20Regression%20Multiclass%2002/ML_Logistic_Regression_Multiclass_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from matplotlib import pyplot as plt
%matplotlib inline

In [37]:
from sklearn.datasets import load_iris
iris = load_iris()

In [38]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [53]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [87]:
iris.target_names[2]

'virginica'

In [56]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [42]:
X = iris.data
y = iris.target

In [43]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2)

In [46]:
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
model.score(X_test, y_test)

0.9666666666666667

In [80]:
model.predict(X_test)

array([1, 2, 2, 0, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 1, 0])

In [81]:
y_test

array([1, 2, 2, 0, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 2, 1, 1, 2,
       1, 1, 2, 2, 2, 1, 1, 0])

In [89]:
X_test[0]

array([5.6, 2.7, 4.2, 1.3])

In [95]:
model.predict([[5.6, 2.7, 4.2, 1.3]])

array([1])

In [90]:
sample = X_test[0].reshape(1, -1)

In [93]:
predicted_class_index = model.predict(sample)
predicted_class_index

array([1])

In [92]:
predicted_class_index = model.predict(sample)[0]
predicted_class_index

1

In [97]:
for i in range(len(X_test)):
    sample = X_test[i].reshape(1, -1)
    predicted_class_index = model.predict(sample)[0]
    predicted_class_name = iris.target_names[predicted_class_index]
    print(f"Sample {i+1} - Predicted class: {predicted_class_name}, Actual class: {iris.target_names[y_test[i]]}")

Sample 1 - Predicted class: versicolor, Actual class: versicolor
Sample 2 - Predicted class: virginica, Actual class: virginica
Sample 3 - Predicted class: virginica, Actual class: virginica
Sample 4 - Predicted class: setosa, Actual class: setosa
Sample 5 - Predicted class: virginica, Actual class: virginica
Sample 6 - Predicted class: setosa, Actual class: setosa
Sample 7 - Predicted class: virginica, Actual class: virginica
Sample 8 - Predicted class: versicolor, Actual class: versicolor
Sample 9 - Predicted class: versicolor, Actual class: versicolor
Sample 10 - Predicted class: setosa, Actual class: setosa
Sample 11 - Predicted class: versicolor, Actual class: versicolor
Sample 12 - Predicted class: versicolor, Actual class: versicolor
Sample 13 - Predicted class: virginica, Actual class: virginica
Sample 14 - Predicted class: setosa, Actual class: setosa
Sample 15 - Predicted class: setosa, Actual class: setosa
Sample 16 - Predicted class: versicolor, Actual class: versicolor
Sam